[package]
name        = "argon-telemetry"
description = "Prometheus metrics for argon-utils"
publish     = false
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
argon-device = { path = "../argon-device", version = "0.1.0" }
argon-hal    = { path = "../argon-hal", version = "0.1.0" }

[lints]
workspace = true
